
# Attention mechanism

In [24]:
import torch

inputs embedded in 3-dimension vector

In [25]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

take 2nd input sequence and use dot product to compute unnormalized attention scores

In [26]:
query = inputs[1]
attn_scores_x2 = torch.empty(inputs.shape[0])
for i, x_1 in enumerate(inputs):
  attn_scores_x2[i] = torch.dot(query, x_1)
  print(attn_scores_x2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.0000, 0.0000])
tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.0000, 0.0000])
tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.0000, 0.0000])
tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.0000, 0.0000])
tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 0.0000])
tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


multiply input sequence x2 with others

In [27]:
result = 0
for idx, element in enumerate(inputs[0]):
    result += inputs[0][idx]*query[idx]
    print(result)
    print('---')
    print(torch.dot(inputs[0], query))

tensor(0.2365)
---
tensor(0.9544)
tensor(0.3670)
---
tensor(0.9544)
tensor(0.9544)
---
tensor(0.9544)


normalize (sum up to 1) the attention score (omega) to attention weights (alpha)
Not preferred due inability to sustain larger value

In [28]:
attn_w2 = attn_scores_x2 / attn_scores_x2.sum()
print("Attention wights:", attn_w2)
print("Sum of attention weights:", attn_w2.sum())

Attention wights: tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Sum of attention weights: tensor(1.0000)


naive can also suffer from instability due to not able to handle under or over flow

In [29]:
def softmax_naive(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)
attn_w2_naive = softmax_naive(attn_scores_x2)
print("Attention wights (naive softmax):", attn_w2_naive)
print("......")
print("Sum of attention weights (naive softmax):", attn_w2_naive.sum())

Attention wights (naive softmax): tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
......
Sum of attention weights (naive softmax): tensor(1.)


softmax is recommended for better result

In [30]:
attn_w2 = torch.softmax(attn_scores_x2, dim=0)
print("Attention wights (softmax):", attn_w2)
print("......")
print("Sum of attention weights (softmax):", attn_w2.sum())

Attention wights (softmax): tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
......
Sum of attention weights (softmax): tensor(1.)


# notes
- weighted sum of input element(x[i to n] with respect to sepecific x(i.e 2)) is context vector (for example z of x(2) is z(2))
- unnormalized attention weights are called scores, when normalized (sum to 1) it is called attention weights
- q = query
- unnormalized attention score (w[omega]) w(21) = x(1)q(2)^T